version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: aldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A Notifications worker -l info -P gevent
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0

volumes:
  postgres_data:
