# Generated by Django 5.0 on 2024-01-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlNotifi', '0007_userprofile_adress_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress',
            new_name='address',
        ),
    ]
