# Generated by Django 5.0 on 2024-01-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlNotifi', '0010_userprofile_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notifications',
        ),
    ]
