# Generated by Django 5.0 on 2024-01-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlNotifi', '0011_remove_userprofile_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
