# Generated by Django 5.0 on 2024-01-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlNotifi', '0012_alter_discordprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordprofile',
            name='discord_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sent_to',
            field=models.CharField(choices=[('discord', 'Discord'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('email', 'Email')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
