# Generated by Django 4.2.9 on 2024-01-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlNotifi', '0013_discordprofile_discord_id_notifications_sent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
