# Generated by Django 4.2.9 on 2024-02-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlNotifi', '0014_alter_discordprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='sent_to',
        ),
    ]
