# Generated by Django 4.2.9 on 2024-02-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlNotifi', '0015_remove_notifications_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
